# Generated by Django 5.0.3 on 2024-03-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_expiration_date',
            field=models.DateField(verbose_name='Date of Expiration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_expiration_date'], name='stock_produ_product_e3b1fc_idx'),
        ),
    ]
